services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    depends_on:
      - llm
  llm:
    image: yb175/pullshark-llm:latest
    expose:
      - "8000"
    restart: unless-stopped

  worker:
    build: ./backend
    command: node worker/analysis.worker.js
    env_file:
      - ./backend/.env
    restart: unless-stopped
    depends_on:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
